### ISSUE TITLE
Zusammenführen aller bisherigen Skripte in ein ganzes

### ISSUE THREAD

**Issue by Jan8192** [ansie3045/Analysis1-KIT-WS23-24-Hundertmark#10]
Wäre es nicht sinnvoll alle bisher vorhandenen Skripte zu einem großen Skript zusammenzufassen, gibt es hierfür irgendwelche schlagkräftigen Argumente die da gegen sprechen. So könnte man das Skript tatsächlich als Nachschlagewerk nutzen und sich nicht durch tausend directories klicken 😃 Würde mich dazu bereit erklären... lmk ob das passt

**Comment by ansie3045** [comment]
Das ist an sich eigentlich ein gute Idee. Ich setzte mich ggf. mal ran, falls ich dazu komme. Es kann sich auch gerne jemad anders darum kümmern.
Ggf. könnte man in diesem Zuge auch die alten Skripte aufs neue Design bringen

**Comment by ansie3045** [comment]
Done

**Comment by ansie3045** [comment]
Done
