### ISSUE TITLE
Automatische Erstellung der PDF

### ISSUE THREAD

**Issue by ansie3045** [ansie3045/Analysis1-KIT-WS23-24-Hundertmark#3]
Falls jemand sich mit GitHub Workflows auskennt, kann er gerne dafür sorgen, dass automatisch die PDF Dateien erstellt werden

**Comment by weisbrja** [comment]
@ansie3045 Ich habe mal mein Bestes gegeben xD

**Comment by ansie3045** [comment]
@weisbrja Hmm, Ich bekomme folgende Fehlermeldung.
![image](https://github.com/ansie3045/Analysis1-KIT-WS23-24-Hundertmark/assets/82664425/8305a35c-76fa-43ad-bc41-9fd86787f339)

`/usr/bin/docker --config /home/runner/work/_temp/.docker_a9d2ee12-0977-4a67-a76d-099cf5ec7690 login ghcr.io -u ansie3045 --password-stdin
  /usr/bin/docker --config /home/runner/work/_temp/.docker_a9d2ee12-0977-4a67-a76d-099cf5ec7690 pull ghcr.io/ansie3045/texlive
  Using default tag: latest
  Error response from daemon: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 5.137 seconds before retry.
  /usr/bin/docker --config /home/runner/work/_temp/.docker_a9d2ee12-0977-4a67-a76d-099cf5ec7690 pull ghcr.io/ansie3045/texlive
  Using default tag: latest
  Error response from daemon: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 3.917 seconds before retry.
  /usr/bin/docker --config /home/runner/work/_temp/.docker_a9d2ee12-0977-4a67-a76d-099cf5ec7690 pull ghcr.io/ansie3045/texlive
  Using default tag: latest
  Error response from daemon: manifest unknown
  Error: Docker pull failed with exit code 1`

Oder muss ich noch was im docker ifle eintragen?

**Comment by weisbrja** [comment]
@ansie3045 Du musst zuerst einmal manuell den Workflow für das Docker Image triggern, sonst gibt es das nicht.

**Comment by weisbrja** [comment]
Ich erklär noch mal kurz, wie das CI funktioniert:

1. Compile Workflow:

Dieser Workflow wird bei jedem Push ausgeführt, kann aber auch manuell getriggert werden (brauch man nur, wenn man das Docker Image neu gebaut hat, also nachdem man den Compile Docker Image Workflow laufen gelassen hat).
Um die LaTeX Dateien zu kompilieren, brauchen wir viele LaTeX Packages.
Die auf Ubuntu zu installieren, ist keine schöne Angelegenheit.
Deswegen pullen wir ein Docker Image, das auf Arch Linux aufbaut und auf dem alles bereits installiert ist und können dann quasi von Arch Linux aus die Dateien kompilieren.

2. Build Docker Image Workflow:

Das Docker Image müssen wir selbst bauen, aber sehr selten (nur wenn neue Packages dazukommen oder wir Updates wollen) und dann halt manuell getriggert.
